stages:
  - deploy

deploy_lambda:
  stage: deploy
  image:
    name: hashicorp/terraform:1.6
    entrypoint: [""]

  id_tokens:
    AWS_OIDC_TOKEN:
      aud: https://gitlab.com

  variables:
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/aws_oidc_token
    AWS_DEFAULT_REGION: "eu-west-1"

  before_script:
    - echo "$AWS_OIDC_TOKEN" > $AWS_WEB_IDENTITY_TOKEN_FILE

  script:
    - cd lambdas/ec2_restart
    - terraform init
    - terraform plan
    - terraform apply -auto-approve

  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
